name: travel_wisata_lokal
description: Aplikasi Travel Wisata Lokal dengan Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Image Picker
  image_picker: ^1.0.4

  # Google Maps
  google_maps_flutter: ^2.5.0

  # UI
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Untuk custom fonts (opsional)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700